### ISSUE TITLE
Build on Ubuntu 16.04

### ISSUE THREAD

**Issue by lucasw** [RuggedScience/SDK#12]
The cmake minimum version prevents this from being built with the cmake in 16.04.

**Comment by RuggedScience** [comment]
@lucasw - It looks like your dev_fixes branch was pulled from master, not dev. Have you tried to see if the dev branch works for your build environment?

dev commit to add support for CMake 2.8 - 9c3e9e3e1db1c6e142a2bb340e6abed8cc4aab37
